#!/bin/bash

if grep -q '#tray_output none #toggle' ~/.config/i3/config
	then
		sed -i 's/#tray_output none #toggle/tray_output none #toggle/g' ~/.config/i3/config
	else
		sed -i 's/tray_output none #toggle/#tray_output none #toggle/g' ~/.config/i3/config
fi
i3-msg restart
