#!/usr/bin/python3
# -*- coding: utf-8 -*-

import re, subprocess

sensor = subprocess.Popen(['sensors'], stdout=subprocess.PIPE).communicate()[0].decode('utf8')

rpm = re.findall('fan[0-9]:[ ]+([0-9]+) RPM', sensor, re.S)[0]

if int(rpm) > 0:
	print(' ' + rpm + ' RPM')
