#!/usr/bin/python3
# -*- coding: utf-8 -*-

import re, subprocess

output = subprocess.Popen(['radeontop', '-l1', '-d-'], stdout=subprocess.PIPE, universal_newlines=True).communicate()[0]

load = re.findall('gpu ([0-9]+\.[0-9]+)%', output, re.S)[0]
vram = re.findall('vram ([0-9]+.[0-9]+)% ([0-9]+\.[0-9]+)mb', output, re.S)[0]
vram_used = float(vram[1]) / 1024
vram_total = vram_used / (float(vram[0]) / 100)

print(' ' + load + '%   ' + '{0:.1f}'.format(vram_used) + '/' + '{0:.1f}'.format(vram_total) + ' GiB')
print(' ' + load + '%')

if float(load) > 80:
	print('ff3300')
