#!/bin/bash

if [ $BLOCK_BUTTON = 1 ]
  then
	i3-nagbar -t warning -m 'Was willst du tun?' -b 'Ausloggen' 'i3-msg exit' -b 'Energie sparen' 'systemctl suspend' -b 'Neustarten' 'reboot' -b 'Herunterfahren' 'poweroff' &> /dev/null
fi

echo " "
